# Generated by Django 4.0.1 on 2022-01-28 16:19

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('spablog', '0003_person_remove_post_tag_post_tag'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(max_length=255)),
                ('created_date', models.DateTimeField(default=datetime.datetime(2022, 1, 28, 16, 19, 15, 545231, tzinfo=utc))),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='spablog.post')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='users', to='spablog.person')),
            ],
            options={
                'ordering': ['-created_date'],
            },
        ),
    ]
